name: 🐛 Bug Report
description: Report a bug or problem
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide the information below to help us quickly reproduce and fix the issue.

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Select the component where the issue occurs
      options:
        - Frontend UI
        - Backend service/API
        - Document Reader Service
        - Vector database
        - Model service
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe the problem in detail
      placeholder: "Describe what happens..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen
      placeholder: "What should happen..."
    validations:
      required: true


  - type: markdown
    attributes:
      value: |
        ## 📋 Log Collection Guide
        
        Please collect relevant logs with the following steps:
        
        **1. App module logs:**
        ```bash
        docker exec -it WeKnowRust-app tail -f /var/log/WeKnowRust.log
        ```
        
        **2. Document reader logs:**
        ```bash
        docker exec -it WeKnowRust-docreader tail -f /var/log/docreader.log
        ```
        
        Reproduce the issue and paste the relevant logs into the field below.

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste logs collected per the guide above
      placeholder: |
        Paste logs collected via:
        - docker exec -it WeKnowRust-app tail -f /var/log/WeKnowRust.log
        - docker exec -it WeKnowRust-docreader tail -f /var/log/docreader.log
      render: shell

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Your current operating system
      placeholder: "e.g., macOS 13, Ubuntu 20.04, Windows 11"
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I have searched existing issues and confirm this is new
          required: true