blank_issues_enabled: false
contact_links:
  - name: WeKnowRust Documentation
    url: https://github.com/SHA888/WeKnoRust/blob/main/docs/QA.md
    about: Read the WeKnowRust FAQ and documentation
  - name: Discussions
    url: https://github.com/SHA888/WeKnoRust/discussions
    about: Ask questions or share ideas in Discussions