name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your feature request! Please describe your proposal in detail to help us understand your needs.

  - type: dropdown
    id: component
    attributes:
      label: Related Component
      description: Select components related to this request
      options:
        - Frontend UI
        - Backend service/API
        - Document Reader Service
        - Vector database
        - Model service
        - Configuration management
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Describe the problem or limitation with current behavior
      placeholder: "What’s wrong or limited with the current behavior?"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature or improvement you would like to see
      placeholder: "How would you like this to be solved?"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe any alternative solutions you’ve considered
      placeholder: "Have you considered other approaches?"

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this request?
      options:
        - Low — nice to have
        - Medium — valuable
        - High — important to workflow
        - Urgent — blocking important work
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this feature would be used
      placeholder: "When would you use this feature?"

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any additional context, screenshots, or links
      placeholder: "Add any other relevant information..."

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I have searched existing issues and confirm this is new
          required: true
        - label: I understand this request may require discussion and evaluation
          required: true