name: ❓ Question
description: Ask a question about WeKnowRust or request help
title: "[Question]: "
labels: ["question", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Welcome! Please provide enough information so we can help effectively.

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Select your question category
      options:
        - Installation & deployment
        - Configuration
        - Usage
        - Performance
        - Integration
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Question
      description: Describe your question in detail
      placeholder: "What did you run into? What help do you need?"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide relevant background
      placeholder: |
        - What are you trying to do?
        - What is the expected result?
        - What have you tried?

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Your current operating system
      placeholder: "e.g., macOS 13, Ubuntu 20.04, Windows 11"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Other Environment Info
      description: Provide any other relevant environment details
      placeholder: |
        - WeKnowRust version: [e.g., v1.0.0]
        - Deployment: [e.g., Docker, source build]
        - Other relevant info...

  - type: markdown
    attributes:
      value: |
        ## 📋 Log Collection Guide (if needed)
        
        If your question involves errors or debugging, please collect logs:
        
        **App module logs:**
        ```bash
        docker exec -it WeKnowRust-app tail -f /var/log/WeKnowRust.log
        ```
        
        **Document reader logs:**
        ```bash
        docker exec -it WeKnowRust-docreader tail -f /var/log/docreader.log
        ```

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: If available, paste related logs or error messages here
      placeholder: "Paste relevant logs or error messages..."
      render: shell

  - type: textarea
    id: research
    attributes:
      label: Prior Research
      description: List documents, issues, or other resources you’ve checked
      placeholder: |
        - Docs reviewed: [e.g., README.md, API.md]
        - Issues reviewed: [e.g., #123, #456]
        - Other resources: [e.g., official docs, Stack Overflow]

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I have searched existing issues and docs
          required: true
        - label: I have provided enough information to understand the problem
          required: true